INSERT INTO category(name, items, type) VALUES ('People', '[
{"name": "Katrin", "picture": ""},
{"name": "Paul", "picture": ""},
{"name": "Charles", "picture": ""},
{"name": "Maria", "picture": ""},
{"name": "Hans", "picture": ""},
{"name": "Peter", "picture": ""},
{"name": "Anne", "picture": ""},
{"name": "Joe", "picture": ""},
{"name": "Daniel", "picture": ""},
{"name": "Sophie", "picture": ""},
{"name": "Michael", "picture": ""},
{"name": "Sarah", "picture": ""},
{"name": "Victor", "picture": ""},
{"name": "Eric", "picture": ""},
{"name": "Lucas", "picture": ""},
{"name": "Thomas", "picture": ""},
{"name": "Frank", "picture": ""},
{"name": "Bernard", "picture": ""},
{"name": "Max", "picture": ""},
{"name": "Roger", "picture": ""},
{"name": "Philippe", "picture": ""},
{"name": "Herman", "picture": ""},
{"name": "Stephen", "picture": ""},
{"name": "Theo", "picture": ""}
]',
'Default');